### ISSUE TITLE
hide avialable tasks

### ISSUE THREAD

**Issue by geoffreysamper** [Sri--/gulp-help-docs#1]
Hi, 
Is there a way for the to hide the tasks in teh task avialable section. In this example the avialable task shows run-tests, compile, run-npm, zip. But I want to hide some tasks like zip and default. Is this possible?

 TASKS AVAILABLE
[09:18:16] run-tests, compile, run-npm, zip, build-deploy, help, default
[09:18:16] TASKS HELP
[09:18:16] run-tests     run all the tests
[09:18:16] build-deploy  prepares a zip for deployment
[09:18:16] help          Displays gulp usage, available tasks and task descriptions

**Comment by Sri--** [comment]
```
gulp.task('help', help.docs.bind(this, gulp.tasks, helpConfig));
```
Yes, it's possible. Since you're passing gulp.tasks (like above), you should be able to filter out or delete certain keys from the object and modify the task. Here's how you could do it:

```
gulp.task('help', function(){
    // Make a copy of the tasks object (do not mutate gulp.tasks)
    var tasks = Object.assign({}, gulp.tasks);

    // Create array of hidden tasks
    var hidden = ['zip', 'default']; 
    hidden.map(function(task){ delete(tasks[task]) });
    
    // Pass in modified copy of tasks
    return help.docs.call(this, tasks, helpConfig);
});

**Comment by geoffreysamper** [comment]
Thx it works
